<a href="https://colab.research.google.com/github/aykahsay/paris-ozone-time-series-forecasting/blob/main/paris-ozone-time-series-forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Time Series Analysis and Forecasting of Ground-Level Ozone (O₃) Concentrations in Paris Using Machine Learning**

In [10]:
from google.colab import userdata

API_KEY = userdata.get("OPENAQ_API_KEY")

In [11]:
import requests
from google.colab import userdata

API_KEY = userdata.get("OPENAQ_API_KEY")

headers = {
    "X-API-Key": API_KEY
}

url = "https://api.openaq.org/v3/locations?city=Los Angeles"

response = requests.get(url, headers=headers)

print(response.status_code)
print(response.json())

200

In [12]:
import requests
from google.colab import userdata

API_KEY = userdata.get("OPENAQ_API_KEY")

headers = {
    "X-API-Key": API_KEY
}

location_id = 4124

url = f"https://api.openaq.org/v3/locations/{location_id}"

response = requests.get(url, headers=headers)

response.json()

{'meta': {'name': 'openaq-api',
  'website': '/',
  'page': 1,
  'limit': 100,
  'found': 1},
 'results': [{'id': 4124,
   'name': 'PARIS 13eme',
   'locality': 'PARIS 13E ARRONDISSEMENT',
   'timezone': 'Europe/Paris',
   'country': {'id': 22, 'code': 'FR', 'name': 'France'},
   'owner': {'id': 4, 'name': 'Unknown Governmental Organization'},
   'provider': {'id': 70, 'name': 'EEA'},
   'isMobile': False,
   'isMonitor': True,
   'instruments': [{'id': 2, 'name': 'Government Monitor'}],
   'sensors': [{'id': 4274755,
     'name': 'no µg/m³',
     'parameter': {'id': 19843,
      'name': 'no',
      'units': 'µg/m³',
      'displayName': 'NO mass'}},
    {'id': 9779,
     'name': 'no2 µg/m³',
     'parameter': {'id': 5,
      'name': 'no2',
      'units': 'µg/m³',
      'displayName': 'NO₂ mass'}},
    {'id': 9782,
     'name': 'o3 µg/m³',
     'parameter': {'id': 3,
      'name': 'o3',
      'units': 'µg/m³',
      'displayName': 'O₃ mass'}}],
   'coordinates': {'latitude': 48.82861000023597,
    'longitude': 2.3602780000847456},
   'licenses': [{'id': 10,
     'name': 'ODC-BY',
     'attribution': {'name': 'Unknown Governmental Organization', 'url': None},
     'dateFrom': '2016-11-17',
     'dateTo': None}],
   'bounds': [2.3602780000847456,
    48.82861000023597,
    2.3602780000847456,
    48.82861000023597],
   'distance': None,
   'datetimeFirst': {'utc': '2016-11-21T12:00:00Z',
    'local': '2016-11-21T13:00:00+01:00'},
   'datetimeLast': {'utc': '2026-07-30T15:00:00Z',
    'local': '2026-07-30T17:00:00+02:00'}}]}

In [13]:
import requests
import pandas as pd
from google.colab import userdata

API_KEY = userdata.get("OPENAQ_API_KEY")

headers = {
    "X-API-Key": API_KEY
}

sensor_id = 9782

url = f"https://api.openaq.org/v3/sensors/{sensor_id}/measurements"

params = {
    "limit": 1000,
    "page": 1
}

response = requests.get(url, headers=headers, params=params)

data = response.json()

print(data["meta"])

{'name': 'openaq-api', 'website': '/', 'page': 1, 'limit': 1000, 'found': '>1000'}

In [17]:
import requests
import pandas as pd
from google.colab import userdata

API_KEY = userdata.get("OPENAQ_API_KEY")

headers = {
    "X-API-Key": API_KEY
}

sensor_id = 9782  # Paris O3 sensor
url = f"https://api.openaq.org/v3/sensors/{sensor_id}/measurements"

all_results = []

for page in range(1, 16):  # Pages 1 to 15
    params = {
        "limit": 1000,
        "page": page
    }

    response = requests.get(url, headers=headers, params=params)
    response.raise_for_status()

    results = response.json()["results"]

    if not results:
        break

    all_results.extend(results)

    print(f"Page {page}: {len(results)} records")

df = pd.DataFrame(all_results)

print(f"\nTotal records: {len(df)}")

Page 1: 1000 records
Page 2: 1000 records
Page 3: 1000 records
Page 4: 1000 records
Page 5: 1000 records
Page 6: 1000 records
Page 7: 1000 records
Page 8: 1000 records
Page 9: 1000 records
Page 10: 1000 records
Page 11: 1000 records
Page 12: 1000 records
Page 13: 1000 records
Page 14: 1000 records
Page 15: 1000 records

Total records: 15000

In [18]:
print(df.head)

<bound method NDFrame.head of        value             flagInfo  \
0      27.50  {'hasFlags': False}
1      56.25  {'hasFlags': False}
2      37.25  {'hasFlags': False}
3      31.75  {'hasFlags': False}
4      38.25  {'hasFlags': False}
...      ...                  ...
14995  81.90  {'hasFlags': False}
14996  62.20  {'hasFlags': False}
14997  56.70  {'hasFlags': False}
14998  54.50  {'hasFlags': False}
14999  49.10  {'hasFlags': False}

                                               parameter  \
0      {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
1      {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
2      {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
3      {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
4      {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
...                                                  ...
14995  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
14996  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
14997  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
14998  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
14999  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...

                                                  period coordinates summary  \
0      {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
1      {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
2      {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
3      {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
4      {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
...                                                  ...         ...     ...
14995  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
14996  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
14997  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
14998  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
14999  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None

                                                coverage
0      {'expectedCount': 1, 'expectedInterval': '01:0...
1      {'expectedCount': 1, 'expectedInterval': '01:0...
2      {'expectedCount': 1, 'expectedInterval': '01:0...
3      {'expectedCount': 1, 'expectedInterval': '01:0...
4      {'expectedCount': 1, 'expectedInterval': '01:0...
...                                                  ...
14995  {'expectedCount': 1, 'expectedInterval': '01:0...
14996  {'expectedCount': 1, 'expectedInterval': '01:0...
14997  {'expectedCount': 1, 'expectedInterval': '01:0...
14998  {'expectedCount': 1, 'expectedInterval': '01:0...
14999  {'expectedCount': 1, 'expectedInterval': '01:0...

[15000 rows x 7 columns]>

In [19]:
print(df.head())

   value             flagInfo  \
0  27.50  {'hasFlags': False}
1  56.25  {'hasFlags': False}
2  37.25  {'hasFlags': False}
3  31.75  {'hasFlags': False}
4  38.25  {'hasFlags': False}

                                           parameter  \
0  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
1  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
2  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
3  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...
4  {'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...

                                              period coordinates summary  \
0  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
1  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
2  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
3  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None
4  {'label': 'raw', 'interval': '01:00:00', 'date...        None    None

                                            coverage
0  {'expectedCount': 1, 'expectedInterval': '01:0...
1  {'expectedCount': 1, 'expectedInterval': '01:0...
2  {'expectedCount': 1, 'expectedInterval': '01:0...
3  {'expectedCount': 1, 'expectedInterval': '01:0...
4  {'expectedCount': 1, 'expectedInterval': '01:0...

In [20]:
df["period"].iloc[0]

{'label': 'raw',
 'interval': '01:00:00',
 'datetimeFrom': {'utc': '2016-11-21T11:00:00Z',
  'local': '2016-11-21T12:00:00+01:00'},
 'datetimeTo': {'utc': '2016-11-21T12:00:00Z',
  'local': '2016-11-21T13:00:00+01:00'}}

In [22]:
df["Date"] = df["period"].apply(lambda x: x["datetimeFrom"]["utc"])
df["Date"] = pd.to_datetime(df["Date"])
df.head()

,value,flagInfo,parameter,period,coordinates,summary,coverage,Date
0,27.50,{'hasFlags': False},"{'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...","{'label': 'raw', 'interval': '01:00:00', 'date...",None,None,"{'expectedCount': 1, 'expectedInterval': '01:0...",2016-11-21 11:00:00+00:00
1,56.25,{'hasFlags': False},"{'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...","{'label': 'raw', 'interval': '01:00:00', 'date...",None,None,"{'expectedCount': 1, 'expectedInterval': '01:0...",2016-11-21 13:00:00+00:00
2,37.25,{'hasFlags': False},"{'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...","{'label': 'raw', 'interval': '01:00:00', 'date...",None,None,"{'expectedCount': 1, 'expectedInterval': '01:0...",2016-11-21 15:00:00+00:00
3,31.75,{'hasFlags': False},"{'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...","{'label': 'raw', 'interval': '01:00:00', 'date...",None,None,"{'expectedCount': 1, 'expectedInterval': '01:0...",2016-11-21 17:00:00+00:00
4,38.25,{'hasFlags': False},"{'id': 3, 'name': 'o3', 'units': 'µg/m³', 'dis...","{'label': 'raw', 'interval': '01:00:00', 'date...",None,None,"{'expectedCount': 1, 'expectedInterval': '01:0...",2016-11-21 19:00:00+00:00

In [23]:
ozone_df = df[["Date", "value"]].copy()

ozone_df.rename(columns={"value": "Ozone"}, inplace=True)

ozone_df.head()

                       Date  Ozone
0 2016-11-21 11:00:00+00:00  27.50
1 2016-11-21 13:00:00+00:00  56.25
2 2016-11-21 15:00:00+00:00  37.25
3 2016-11-21 17:00:00+00:00  31.75
4 2016-11-21 19:00:00+00:00  38.25